language: go

install:
  - bundle install
  - mkdir ~/bin
  - curl https://github.com/gohugoio/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.tar.gz -O hugo.tgz
  - tar xfv hugo.tgz -C bin
  - rm hugo.tgz bin/*.md
  - export PATH=$HOME/bin:$PATH

script:
  - gem install jekyll-sitemap
  - gem install jekyll-feed
  - gem install jekyll-paginate
  - jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: <name folder website yang dibangun>
  target_branch: gh-pages
  on:
    branch: master
